[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = ['python -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Python FastAPI project ready"']

[start]
cmd = 'python start.py'
