[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
PORT = "5000"
NODE_ENV = "production"

[environments.staging]
PORT = "5000"
NODE_ENV = "staging"
